"""empty message

Revision ID: f0c6837233e5
Revises: f508e538efb7
Create Date: 2025-07-08 15:13:00.971344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c6837233e5'
down_revision: Union[str, Sequence[str], None] = 'f508e538efb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'phone_number',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'phone_number',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)
    # ### end Alembic commands ###
